'use client';
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { ClerkProvider, RedirectToSignIn, SignedOut } from '@clerk/nextjs'
import { useState } from "react";
import { Toaster } from "sonner";

const inter = Outfit({ subsets: ["latin"] });

//  export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
//   };

export default function RootLayout({ children }) {
  
  const[showAuth, setShowAuth] = useState(false);
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    rootUrl="https://localhost:3000">
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-6 md:mx-16">
          <Header onAuthButtonClick={() => setShowAuth(true)}/>
          <Toaster />
        {children}
        </div>
        {showAuth && <RedirectToSignIn />}
        </body>    
    </html>
    </ClerkProvider>
    
  );
}
